parrot_paraphraser:
  _target_: reliability_score.augmentation.augments.parrot_paraphraser
  _partial_: true
  __name__: "parrot"
  dataset_name: ${datamodule.dataset_specific_args.name}
  csv_path: "./data/parrot_{}.csv"
  cols: ${datamodule.dataset_specific_args.cols}
