accuracy_callback:
  _target_: reliability_checklist.callbacks.evals.discriminative.AccuracyMetric
  monitor: "all"
  results_dir: ${paths.result_dir}
  override: null
  radar: ${callbacks.radar_data}
  max_possible: 100
  inverse: false
