calibration_callback:
  _target_: reliability_checklist.callbacks.evals.discriminative.CalibrationMetric
  monitor: "all"
  results_dir: ${paths.result_dir}
  num_bins: 10
  override: null
  radar: ${callbacks.radar_data}
  max_possible: 0.5
  inverse: true
