sensitivity_callback:
  _target_: reliability_checklist.callbacks.evals.discriminative.SensitivityMetric
  monitor: "all"
  results_dir: ${paths.result_dir}
  override: "mixed"
  radar: ${callbacks.radar_data}
  max_possible: dynamic
  inverse: true
