# @package _global_

# to execute this experiment run:
# python train.py experiment=example

defaults:
  - override /datamodule: mrpc.yaml
  - override /model: inference.yaml
  - override /callbacks: general_evals.yaml
  - override /trainer: default.yaml
  - override /custom_model: bert_base_uncased_mrpc.yaml
  - override /augmentation: mrpc.yaml

# all parameters below will be merged with parameters from default configurations set above
# this allows you to overwrite only specified parameters

tags: ["mrpc", "test"]

seed: 42
