# @package _global_

# to execute this experiment run:
# python train.py experiment=example

defaults:
  - override /augmentation: sentiment.yaml
  - override /datamodule: sentiment140.yaml
  - override /model: inference.yaml
  - override /callbacks: general_evals.yaml
  - override /trainer: default.yaml
  - override /custom_model: bert_base_uncased.yaml
  - override /logger: wandb.yaml

# all parameters below will be merged with parameters from default configurations set above
# this allows you to overwrite only specified parameters

tags: ["sentiment", "test"]

seed: 42
