sensitivity_callback:
  _target_: reliability_score.callbacks.evals.discriminative.SensitivityMetric
  monitor: "all"
  results_dir: ${paths.result_dir}
  override: "mixed"
  radar: true
  max_possible: dynamic
  inverse: true
